version: 2
updates:
  # Maintain dependencies for Github Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "07:00"
